rm(list=ls())

if (!requireNamespace("BiocManager", quietly=TRUE))
  install.packages("BiocManager")
BiocManager::install("minfi")
BiocManager::install("IlluminaHumanMethylation27kmanifest")
BiocManager::install("IlluminaHumanMethylation450kmanifest")
BiocManager::install("IlluminaHumanMethylationEPICmanifest")
BiocManager::install("IlluminaHumanMethylationMSAmanifest")
BiocManager::install("IlluminaHumanMethylation27kanno.ilmn12.hg19")
BiocManager::install("IlluminaHumanMethylation450kanno.ilmn12.hg19")
BiocManager::install("IlluminaHumanMethylationEPICanno.ilm10b4.hg19")
BiocManager::install("IlluminaHumanMethylationEPICv2anno.20a1.hg38")
BiocManager::install("IlluminaHumanMethylationMSAanno.ilm10a1.hg38")
install.packages("openxlsx")

library(minfi)
library(openxlsx)
library(IlluminaHumanMethylation27kmanifest)
library(IlluminaHumanMethylation450kmanifest)
library(IlluminaHumanMethylationEPICmanifest)
library(IlluminaHumanMethylationMSAmanifest)
library(IlluminaHumanMethylation27kanno.ilmn12.hg19)
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(IlluminaHumanMethylationEPICv2anno.20a1.hg38)
library(IlluminaHumanMethylationMSAanno.ilm10a1.hg38)

path <- "E:/YandexDisk/Work/pydnameth/datasets"

ann27k <- getAnnotation(IlluminaHumanMethylation27kanno.ilmn12.hg19)
ann450k <- getAnnotation(IlluminaHumanMethylation450kanno.ilmn12.hg19)
ann850k <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
annepicv2 <- getAnnotation(IlluminaHumanMethylationEPICv2anno.20a1.hg38)
annmsa <- getAnnotation(IlluminaHumanMethylationMSAanno.ilm10a1.hg38)

fn_save = paste(path, "/27k.xlsx",  sep='')
write.xlsx(ann27k, fn_save, sheetName = "Sheet1", col.names = TRUE, row.names = FALSE, append = FALSE)
fn_save = paste(path, "/450k.xlsx",  sep='')
write.xlsx(ann450k, fn_save, sheetName = "Sheet1", col.names = TRUE, row.names = FALSE, append = FALSE)
fn_save = paste(path, "/850k.xlsx",  sep='')
write.xlsx(ann850k, fn_save, sheetName = "Sheet1", col.names = TRUE, row.names = FALSE, append = FALSE)
fn_save = paste(path, "/epicv2.xlsx",  sep='')
write.xlsx(annepicv2, fn_save, sheetName = "Sheet1", rowNames = TRUE, colNames = TRUE, append = FALSE)
fn_save = paste(path, "/msa.xlsx",  sep='')
write.xlsx(annmsa, fn_save, sheetName = "Sheet1", rowNames = TRUE, colNames = TRUE, append = FALSE)
